news:
  msg:
    bad: 'bad news from /config/application.yml :('
    good: 'good news from /config/application.yml :)'

spring:
  jackson:
    date-format: "EEE, d MMM yyyy HH:mm:ss Z"
  profiles:
    active: prod


management:
  endpoints:
    web:
      exposure:
        include: health, info


# Configuring: info endpoint
info:
  app:
    description: This is my first spring boot application
    name: demo-app-news
